---
title: "EDA"
output: pdf_document
---
Importing libraries
```{r include=FALSE}
library(ggplot2)
library(knitr)
library(tidyverse)
library(dplyr)
library(kableExtra)
```

Loading Data
```{r}
load('./30103-0001-Data.rda')
df <- da30103.0001
#names(df)
#str(df)
```

Data Cleaning
```{r cols-to-keep}
keeps <- c('RESPONDENT_YRSED',# Approx Respondent yrs education based on ppeduc, first demographic survey
           'PARTNER_YRSED',   #Partner yrs education based on q10
           'PPINCIMP',        #Binned - total combined household income
           'PPWORK',          #employment
           'QFLAG',           # does person have a partner?
           'PAPGLB_STATUS',   #(gay, lesbian, or bisexual)
           'PPMARIT',         # marital status
           'PPGENDER',        # gender
           'Q4',              #( is partner female or male) 
           'Q5',              #(is partner same gender)
           'Q23',             # between you and [partner_name], who earned more income in 2008
           'PPETHM',          # race/ethnicity
           'Q6B',             # race of partner
           'RESPONDENT_RACE',
           'PARTNER_RACE',
           'RELATIONSHIP_QUALITY', # relationship quality, based on q34, higher number is better
           'PPGENDER', #gender
           'PPREG4', #based on state of residence
           'PPREG9', #based on state of residence
           'PPWORK', #current employment status
           'SAME_SEX_COUPLE' #same sex couple
           )

# store as new df
df <- df[keeps]

# only keep the partnered people
df <- df[df$QFLAG=='(1) partnered',]

```

Data Transformation
```{r add-col}
# add a new column to track difference in education
df['diff_in_education'] = df$RESPONDENT_YRSED - df$PARTNER_YRSED

# add boolean to track difference in race
df['diff_in_race'] = ifelse(df$RESPONDENT_RACE == df$PARTNER_RACE, 0, 1)

# add boolean to track difference in income
df['diff_in_income'] = ifelse(df$Q23 == '(2) we earned about the same amount', 0, 1)

#add Relationship quality
```

Relationship Quality
```{r}
glimpse(df$RELATIONSHIP_QUALITY)

summary(df$RELATIONSHIP_QUALITY)

ggplot(df, aes(RELATIONSHIP_QUALITY)) + geom_bar() + theme_bw() + xlab("Relationship Quality") + ylab("Count") 

NA %in% df$RELATIONSHIP_QUALITY
sum(is.na(df$RELATIONSHIP_QUALITY))

#There's 13 NA values for relationship quality - removing them
df[!is.na(df$RELATIONSHIP_QUALITY), ]
na.omit(df, cols = 'RELATIONSHIP_QUALITY')

#ggplot(df, aes(RELATIONSHIP_QUALITY)) + geom_bar() + theme_bw() + xlab("Relationship Quality") + ylab("Count") 
```

Current Employment Status
```{r}
table(df$PPWORK)

ggplot(df, aes(PPWORK)) + geom_bar() + theme_bw() + xlab("Current Employment Status") + ylab("Count") + theme(legend.position = "bottom") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

GLB Status
```{r}
table(df$PAPGLB_STATUS)

ggplot(df, aes(PAPGLB_STATUS)) + geom_bar() + theme_bw() + xlab("GLB Status") + ylab("Count") + theme(legend.position = "bottom")

```

Same Sex couple
```{r}

table(df$SAME_SEX_COUPLE)

ggplot(df, aes(SAME_SEX_COUPLE)) + geom_bar() + theme_bw() + xlab("Same Sex Couple") + ylab("Count") + theme(legend.position = "bottom")

```

